### ISSUE TITLE
please add higher resolution demo images to github

### ISSUE THREAD

**Issue by fiendish** [DeepPhe/DeepPhe-Viz#32]
The screenshots shown in the README are too small/pixelated to easily evaluate. Can you please include high resolution screenshots?

**Comment by yuanzhou** [comment]
Thanks for pointing this out. The two screenshots of the DeepPhe-Viz tool are mainly used to show the major sections of the UI. We'll capture high-res screenshots when we do the next release.

**Comment by yuanzhou** [comment]
A higher resolution demo images have been added and will be released in a few days.
